version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  trade:
    executor: python-executor
    environment:
      QUANTITY: << pipeline.parameters.QUANTITY >>
      TAKE_PROFIT: << pipeline.parameters.TAKE_PROFIT >>
      STOP_LOSS: << pipeline.parameters.STOP_LOSS >>
      TESTNET_URL: << pipeline.parameters.TESTNET_URL >>
      POLLING_INTERVAL: << pipeline.parameters.POLLING_INTERVAL >>
      APP_PASSWORD: << pipeline.parameters.APP_PASSWORD >>
      TESTNET_API_KEY: << pipeline.parameters.TESTNET_API_KEY >>
      TESTNET_API_SECRET: << pipeline.parameters.TESTNET_API_SECRET >>
      EMAIL_USERNAME: << pipeline.parameters.EMAIL_USERNAME >>
      EMAIL_SENDERS: << pipeline.parameters.EMAIL_SENDERS >>

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run trading script
          command: python3 email_listener.py

workflows:
  scheduled-trading:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"  # Runs every 5 minutes
          filters:
            branches:
              only: main
    jobs:
      - trade

    # Add a default workflow to run on commits
  build-and-test:
    jobs:
      - trade
