version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  trade:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run trading script
          command: python3 email_listener.py

workflows:
  scheduled-trading:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"  # Runs every 5 minutes
          filters:
            branches:
              only: main
    jobs:
      - trade

    # Add a default workflow to run on commits
  build-and-test:
    jobs:
      - trade
